title: Aniket Rajnish


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "© Makra"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/" 
 - name: "Resume"
   link: "/files/AR_Resume.pdf"
 - name: "Contact"
   link: "/contact"
 - name: "Docs"
   link: "/docs"
 
